server:
  port: 9021

spring:
  profiles:
    active: mongodb, fdfsBasePathNginx
  application:
    name: oceanopedia-search
  elasticsearch:
    uris: http://111.231.19.137:9200

oceanopedia:
  banner:
    nginx:
      prefix: http://111.231.19.137:8888/
  fdfsBasePath:
    nginx:
      prefix: http://111.231.19.137:8888/
  search:
    init:
      enabled: true