server:
  port: 4007

spring:
  application:
    name: oceanopedia-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # oceanopedia-multimedia
        - id: multimedia-getBanners
          uri: lb://oceanopedia-multimedia
          predicates:
            - Path=/multimedia/getBanners
        - id: multimedia-uploadImageNoPrefix
          uri: lb://oceanopedia-multimedia
          predicates:
            - Path=/multimedia/uploadImageNoPrefix

        # oceanopedia-user
        - id: user
          uri: lb://oceanopedia-user
          predicates:
            - Path=/user/login
        - id: register
          uri: lb://oceanopedia-user
          predicates:
            - Path=/user/register
        - id: deleteUserById
          uri: lb://oceanopedia-user
          predicates:
            - Path=/user/deleteUserById
        - id: sendVerificationCode
          uri: lb://oceanopedia-user
          predicates:
            - Path=/user/sendVerificationCode
        - id: getUsers
          uri: lb://oceanopedia-user
          predicates:
            - Path=/user/getUsers
        - id: getUserByUsername
          uri: lb://oceanopedia-user
          predicates:
            - Path=/user/getUserByUsername
            - Query=username
        - id: getUserById
          uri: lb://oceanopedia-user
          predicates:
            - Path=/user/getUserById
            - Query=id
        
        # oceanopedia-article
        - id: article-getArticleByID
          uri: lb://oceanopedia-article
          predicates:
            - Path=/article/getArticleByID
            - Query=id
        - id: article-addArticle
          uri: lb://oceanopedia-article
          predicates:
            - Path=/article/addArticle
        - id: article-deleteArticleByID
          uri: lb://oceanopedia-article
          predicates:
            - Path=/article/deleteArticleByID
        - id: article-getArticlesByCategory
          uri: lb://oceanopedia-article
          predicates:
            - Path=/article/getArticlesByCategory
        - id: article-updateArticleStatusById
          uri: lb://oceanopedia-article
          predicates:
            - Path=/article/updateArticleStatusById
        - id: article-updateArticleInfoById
          uri: lb://oceanopedia-article
          predicates:
            - Path=/article/updateArticleInfoById
        - id: article-updateArticleCoverImageById
          uri: lb://oceanopedia-article
          predicates:
            - Path=/article/updateArticleCoverImageById
        - id: article-getArticleByLikesRank
          uri: lb://oceanopedia-article
          predicates:
            - Path=/article/getArticleByLikesRank
    config:
      uri: http://localhost:8764
      label: master
      name: oceanopedia
      profile: dev