server:
  port: 8764

spring:
  application:
    name: oceanopedia-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Palpatine0/Oceanopedia.git
          search-paths:
            - oceanopedia-config
      label: master

logging:
  pattern:
    console: '%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'