server:
  port: 8764

spring:
  application:
    name: oceanopedia-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Palpatine0/Oceanopedia.git
          search-paths:
            - oceanopedia-config
      label: master