server:
  port: 9022

spring:
  application:
    name: oceanopedia-user
  profiles:
    active: redis,mongodb
  cloud:
    config:
      uri: http://localhost:8764
      label: master
      name: oceanopedia
      profile: dev