server:
  port: 9020

spring:
  application:
    name: oceanopedia-multimedia
  profiles:
    active: mongodb
  cloud:
    config:
      uri: http://localhost:8764
      label: master
      name: oceanopedia
      profile: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: refresh

oceanopedia:
  fdfsBasePath:
    nginx:
      prefix: http://111.231.19.137:8888/

fdfs:
  so-timeout: 10000
  connect-timeout: 10000
  fileUrl: http://111.231.19.137:8888/
  tracker-list:
    - 111.231.19.137:22122
  pool:
    max-total: 200
    max-total-per-key: 50
    max-wait-millis: 5000
