server:
  port: 9023
  
spring:
  application:
    name: oceanopedia-article
  profiles:
    active: mongodb, redis, fdfsBasePathNginx, bannerNginx
  cloud:
    config:
      uri: http://localhost:8764
      label: master
      name: oceanopedia
      profile: dev

eureka:
  server:
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

oceanopedia:
  banner:
    nginx:
      prefix: http://111.231.19.137:8888/
  fdfsBasePath:
    nginx:
      prefix: http://111.231.19.137:8888/